(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
// Three-step estimate. No personal details, requests or persistent storage.
const state={step:0,service:null,need:null,support:null};const labels={web:'ホームページづくり',ai:'AI導入・活用',unsure:'何から始めるか相談'};
const plans={web:{title:'ホームページ制作',price:330000,items:['対話2回・構成と原稿の作成','5ページ程度までの設計・デザイン・実装','スマホ対応・公開・操作説明'],note:'撮影・ドメイン・サーバーなどの実費、追加機能は別途お見積もりします。'},creative:{title:'映像・独自演出を含むサイト制作',price:550000,items:['ホームページ制作の基本内容','映像の企画・生成・編集','スクロールに合わせた独自の演出'],note:'場面数やページ数、機能によって費用が変わります。撮影・ドメイン・サーバーなどの実費は別途です。'},audit:{title:'AI活用の棚卸し',price:33000,fixed:true,items:['90分の対話で業務を整理','AIを活用する候補と優先順位の提案','次に進める内容の整理'],note:'導入・開発・研修の費用は含みません。必要な支援を確認して、別途お見積もりします。'},implement:{title:'AI導入・業務改善',price:165000,items:['対象業務1つの設計・設定・実装','実際の使い方の説明','導入後30日の質問対応'],note:'AIツールの利用料・API料金は別途です。複数業務や追加開発は別途お見積もりします。'},training:{title:'AI実践研修',price:165000,fixed:true,items:['事前ヒアリング','3時間・5名までの業務に合わせた演習','仕事の中での使い方を整理'],note:'AIツールの利用料、訪問時の交通費は別途です。人数や研修時間の追加はお見積もりします。'},talk:{title:'まずは、相談内容を整理するところから。',price:null,items:['考えていること、困っていることを聞かせてください','必要な支援と、その範囲を一緒に確認','有料の支援に進む前に、内容と費用をご案内'],note:'この段階では金額を決めず、内容を伺ってからご案内します。'}};
function option(value,title,desc=''){return '<button class="option" type="button" data-value="'+value+'"><span><strong>'+title+'</strong>'+(desc?'<small>'+desc+'</small>':'')+'</span><span aria-hidden="true">↗</span></button>'}
function render(focus=true){const body=$('#quiz-body');$('#quiz').hidden=false;$('#quiz-count').textContent=state.step<3?'質問 '+(state.step+1)+' / 3':'相談の入口と費用の目安';$$('.dots i').forEach((x,i)=>x.classList.toggle('active',state.step>=i));$('#quiz-back').hidden=state.step===0;$('#quiz-back').textContent=state.step===3?'← 選び直す':'← ひとつ戻る';$('#quiz-help').textContent=state.step===3?'この診断でお申し込みにはなりません。':'近いものを選んでください。';
if(state.step===0){body.innerHTML='<h3 tabindex="-1">今、気になっていることは？</h3><div class="quiz-options">'+option('web','ホームページをつくりたい','新しくつくる・今のサイトを見直す')+option('ai','仕事にAIを取り入れたい','業務の整理・導入・使い方を学ぶ')+option('unsure','まだ、うまく言葉にできない','話しながら整理したい')+'</div>';}
if(state.step===1){let opts;if(state.service==='web')opts=option('web','事業が伝わるサイトをつくる','言葉・構成・デザインから相談')+option('creative','映像や動きにも、こだわりたい','独自の表現までつくり込みたい')+option('talk','まずは必要な内容を相談したい');else if(state.service==='ai')opts=option('audit','どの仕事に使えるか、整理したい','業務の棚卸しと導入方針')+option('implement','具体的な仕事を、使いやすくしたい','1つの業務への導入・仕組みづくり')+option('training','自分やチームで、使い方を学びたい','業務に合わせた実践研修');else opts=option('talk','事業の伝え方を相談したい')+option('audit','仕事の困りごとを整理したい')+option('talk','何を頼めるか聞いてみたい');body.innerHTML='<h3 tabindex="-1">どんなところから始めたいですか？</h3><div class="quiz-options">'+opts+'</div>';}
if(state.step===2){const website=['web','creative'].includes(state.need)||state.service==='web';body.innerHTML='<h3 tabindex="-1">その後のサポートは？</h3><div class="quiz-options">'+option('none','まずは、今回の内容だけ','継続サポートはつけずに考える')+option('ongoing',website?'公開後の更新も、相談したい':'使い続けながら、相談したい',website?'文章・画像の軽微な更新':'活用の振り返り・改善・質問')+option('later','話してから決めたい','今は決めなくて大丈夫です')+'</div>';}
if(state.step===3){const p=plans[state.need],web=['web','creative'].includes(state.need)||state.service==='web',monthly=state.support==='ongoing'&&p.price!==null?(web?11000:55000):0;const price=p.price===null?'<p class="body-copy">内容を伺ってから、お見積もりします。</p>':'<p class="price-label">初期費用の目安（税込）</p><p class="price">'+(p.price/10000).toLocaleString('ja-JP')+'<small>万円'+(p.fixed?'':'〜')+'</small></p>';const m=monthly?'<p class="monthly">継続サポート：<strong>月'+(monthly/10000)+'万円〜（税込）</strong><br><small>'+(web?'軽微な文章・画像更新、月2件まで。':'月1回90分の面談＋チャット・改善。月5時間相当まで。新規開発は別途。')+'</small></p>':'<p class="monthly">'+(state.support==='none'?'継続サポートは含みません。':'継続サポートの内容・費用は相談後に決定。')+'</p>';body.innerHTML='<div class="result"><p class="result-eyebrow">あなたの相談の入口</p><h3 tabindex="-1">'+p.title+'</h3><p class="selection">'+labels[state.service]+' ／ '+(state.support==='ongoing'?'継続サポートを希望':state.support==='none'?'今回の内容のみ':'継続は相談後に')+'</p>'+price+m+'<ul class="result-list">'+p.items.map(x=>'<li>'+x+'</li>').join('')+'</ul><p class="result-note">'+p.note+'<br>これは概算です。正式な金額・期間・対応範囲は、ご相談後のお見積もりで確定します。</p><a class="pill" href="#contact">この内容で、話してみる <span aria-hidden="true">↗</span></a><br><button type="button" class="plain-button" id="restart">最初からやり直す</button></div>';$('#restart').addEventListener('click',()=>{Object.assign(state,{step:0,service:null,need:null,support:null});render()});}
body.querySelectorAll('[data-value]').forEach(b=>b.addEventListener('click',()=>{const value=b.dataset.value;if(state.step===0){state.service=value;state.need=null;state.support=null}else if(state.step===1){state.need=value;state.support=null}else state.support=value;state.step++;render()}));if(focus){body.querySelector('h3').focus({preventScroll:true});if($('#quiz').getBoundingClientRect().top<0)$('#quiz').scrollIntoView({behavior:'instant',block:'start'})}}
$('#quiz-back').addEventListener('click',()=>{if(state.step>0)state.step--;render()});$$('[data-start]').forEach(a=>a.addEventListener('click',()=>{Object.assign(state,{step:1,service:a.dataset.start,need:null,support:null});render(false)}));render(false);
})();
